# -*- coding: utf-8 -*-
"""EM_AP_PU.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17y5OKktKvfPVqH7sLKBI7tr9uNGR12B3
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

def dot(a, b):
    return np.dot(a, b)

def norm(a):
    return np.linalg.norm(a)

def load_embedding_vectors_glove(filename, vector_size):
    f = open(filename,encoding='utf-8',errors='ignore')
    dic = {}
    word_list = []
    for line in f:
        values = line.split()
        word = values[0]
        word = str(word)
        word_list.append(word)
        vector = np.asarray(values[1:], dtype="float32")
        dic[word] = vector
    f.close()
    return dic, word_list

def NextWordFinding(embedding, words):
    pre_list = ['বাংলাদেশ', 'চট্টগ্রাম', 'প্রেম']
    for i in range(len(pre_list)):
        word = str(pre_list[i])
        word_embed1 = embedding[word]
        best = -100
        par = ''
        for j in range(len(words)):
            word1 = str(words[j])
            if word==word1:
                continue
            word_embed2 = embedding[word1]
            cos_sim = dot(word_embed1, word_embed2) / (norm(word_embed1) * norm(word_embed2))
            if cos_sim > best and cos_sim>0.7:
                best = cos_sim
                par = word1
                print(word," ", word1, " :", cos_sim)

def SimanticSimilarity(dic):
    words = ['আসমান আকাশ', 'জল পানি', 'মরণ  নিহত', 'মরণ ফোন', 'আইফোন  ফোন', 'আইফোন  নিহত', 'আইফোন  ক্যামেরা']
    for i, word in enumerate(words):
        word = word.split()
        w1 = word[0]
        w2 = word[1]
        if w1 not in dic:
          print(w1," is OOV Word")
          continue
        if w2 not in dic:
          print(w2," is OOV Word")
          continue
        v1 = dic[w1]
        v2 = dic[w2]
        cos_sim = dot(v1, v2) / (norm(v1) * norm(v2))
        print(w1," ",w2, " :", cos_sim)

    return

def SyntacticSimilarity(dic):
    words = ['অভিভাবকরা অভিভাবক', 'অভিভাবক নিহত', 'শিক্ষক শিক্ষকরা', 'আপনি আপনারা', 'শিক্ষকরা পাইলটরা']
    for i, word in enumerate(words):
        word = word.split()
        w1 = word[0]
        w2 = word[1]
        if w1 not in dic:
          print(w1," is OOV Word")
          continue
        if w2 not in dic:
          print(w2," is OOV Word")
          continue
        v1 = dic[w1]
        v2 = dic[w2]
        cos_sim = dot(v1, v2) / (norm(v1) * norm(v2))
        print(w1," ",w2, " :", cos_sim)

    return

embedding, word_list = load_embedding_vectors_glove('/content/drive/MyDrive/Embedding/GloVe.txt',300)

SimanticSimilarity(embedding)

SyntacticSimilarity(embedding)

NextWordFinding(embedding, word_list)

